Ch. 5 Web Fonts
semanticmx/css-11122021 pull request #5
Opened 2021-11-16 07:12 UTC by JosephColinP

## what

- Added files to describe what are Web Fonts

## why

- This PR was created to know what are Web Fonts and how they work.

## References

- (Ch. 5 Pg. 47) http://bedford-computing.co.uk/learning/wp-content/uploads/2016/07/No.Starch.CSS.2nd.Edition.pdf

2021-11-19 15:23 UTC, semanticmx requested changes
muy bien

2021-11-19 15:23 UTC, semanticmx commented on ch5-webfonts/style.css
> +* {
@JosephColinP estos estilos qué hacen?

2021-11-19 15:23 UTC, semanticmx commented on ch5-webfonts/style.css
> +  margin-bottom: 20px;
hay una estrategia de desarrollo que se llama factorizar, en donde los factores comunes se aislan para evitar repetición.

Por ejemplo:

```
p {
 margin-bottom: 20px;
}
.box {
 ..
 margin-bottom: 20px;
 ..
}
```

Puede factorizarse en:

```
.mb-20 {
 margin-bottom: 20px;
}
.box {
 ..
 ..
}
```
Al momento de aplicarlos quedaría así

```
<p class="mb-20"></p>
<div class="box mb-20"></div>
```

Entonces hay que factorizar los ejemplos para evitar repetir estilos

2021-11-19 15:23 UTC, semanticmx commented on ch5-webfonts/style.css
> +  font-family: "cream";
este es otro buen candidato para factorizar

2021-11-19 15:42 UTC, semanticmx commented
Muy bien @JosephColinP vamos a actualizar el PR template para agregar la sección de `responsive`, donde solo se agregan los screenshot en resoluciones móvil y tablet (landscape y portrait) por favor.

2021-11-19 17:31 UTC, JosephColinP commented on ch5-webfonts/style.css
> +* {
Primero uso el selector * que seleciona todos los elementos.
Despúes defino el margin y el padding a 0 para ajustarlos despues al tamaño que quiera.
Por último el box-sizing hace que el border y el padding se incluyan en el width definido. Hay dos values, uno de ellos hace que cuando se le agregue un padding de 5px se le añadan esos 5 px al width original, descuadrando todo. Y el value que puse hace que al agregar un padding de 5px se incluya dentro del width original

2021-11-19 17:40 UTC, JosephColinP commented
> Muy bien @JosephColinP vamos a actualizar el PR template para agregar la sección de `responsive`, donde solo se agregan los screenshot en resoluciones móvil y tablet (landscape y portrait) por favor.

Entonces hago las páginas responsivas ? agregando mobile y tablet + landscape?

2021-11-19 20:09 UTC, JosephColinP commented on ch5-webfonts/style.css
> +  font-family: "cream";
Para factorizar el @font-face solo pongo dos puntos ? es que no me sale

2021-11-19 20:17 UTC, JosephColinP commented
Tengo otra pregunta, el diseño responsivo será para todos los PR en adelante ? para ir haciendo todas las demás responsivas.

2021-11-20 16:06 UTC, semanticmx commented on ch5-webfonts/style.css
> +* {
estos estilos generalmente se utilizan para configurar los valores iniciales de los estilos para asignarles un default, esto debido a que dependiendo del navegador que se utilice los estilos aplicados pueden verse distintos justo porque cada navegador les asigna diferentes valores de inicio o interpreta los valores no asignados de diferente forma.

Dicho esto, hay que crear una nueva hoja de estilo que se llame reset.css y colocar estos estilo ahí.

2021-11-20 16:08 UTC, semanticmx commented
> Tengo otra pregunta, el diseño responsivo será para todos los PR en adelante ? para ir haciendo todas las demás responsivas.

SI, por default todos nuestros sitios son responsive, entonces de este PR en adelante hay que verificar que se desplieguen bien en mobil y tablet también

2021-11-20 16:10 UTC, semanticmx requested changes

2021-11-20 16:10 UTC, semanticmx commented on ch5-webfonts/styles.css
> +@font-face {
el CSS se aplica en "cascada" por lo que los estilos diferentes declarados en diferentes secciones se acumulan y los estilos previamente declarados son reemplazados por el último que se defina.

El `@font-face` de la línea 1 se reemplaza por el de la línea 6, por lo que podemos eliminar las líneas 1 a la 4

2021-11-20 17:22 UTC, JosephColinP commented on ch5-webfonts/styles.css
> +@font-face {
Ah ya vale vale, pero en este caso no o si? es que le puse la diferencia a uno el "font-stretch: 1% 500%;" para que se despliegue en chrome y se vea la diferencia

2021-11-23 14:47 UTC, semanticmx commented on ch5-webfonts/styles.css
> +@font-face {
Si, es este caso es el último bloque el que se toma en cuenta ya que sobre-escribe 2 propiedades que declaraste antes y agrega una tercera.

2021-11-23 17:55 UTC, JosephColinP commented on ch5-webfonts/styles.css
> +@font-face {
Vale. Entonces solo borro la linea de 1 a la 4 ? :thinking:

2021-11-23 18:10 UTC, semanticmx commented on ch5-webfonts/styles.css
> +@font-face {
si, par que queden solo la de la línea 6

2021-11-24 02:09 UTC, JosephColinP commented on ch5-webfonts/styles.css
> +@font-face {
ya lo borré, pero algo ando haciendo mal, sigo sin entenderle, ya borré las lineas pero no agarra el código que tenía antes

2021-11-24 02:10 UTC, JosephColinP commented on ch5-webfonts/styles.css
> +@font-face {
Ya quedó, pero algo ando haciendo mal, porque borré las lineas, pero no está detectando el código que habia antes

2021-11-24 14:49 UTC, semanticmx commented on ch5-webfonts/styles.css
> +@font-face {
checale bien, aquí hay un ejemplo:

https://developer.mozilla.org/en-US/docs/Web/CSS/font-stretch#examples

Ya cuando haya quedado el diseño me avisas para cerrar el PR

2021-11-24 17:26 UTC, JosephColinP commented on ch5-webfonts/styles.css
> +@font-face {
Ya quedó :+1:

2021-11-24 17:47 UTC, merged