Ch. 7 Multiple Columns
semanticmx/css-11122021 pull request #7
Opened 2021-11-16 07:32 UTC by JosephColinP

## what

- Added files to describe how columns works

## why

- This PR was created to know what are columns, how to create layouts, and how they work.

## References

- (Ch. 7 Pg. 75) http://bedford-computing.co.uk/learning/wp-content/uploads/2016/07/No.Starch.CSS.2nd.Edition.pdf

2021-12-07 01:09 UTC, semanticmx commented
@JosephColinP en móvil por default siempre se muestra una sola columna.

Para optimizar el ancho del dispositivo y ayudar con la lectura de textos

2021-12-07 01:12 UTC, semanticmx requested changes

2021-12-07 01:12 UTC, semanticmx commented on ch7-multiple-columns/css/styles.css
> +  margin: 0 auto;
hay que ordenar estas

2021-12-07 01:12 UTC, semanticmx commented on ch7-multiple-columns/css/styles.css
> +  color: white;
el color a RGB

2021-12-07 01:12 UTC, semanticmx commented on ch7-multiple-columns/index.html
> +        <div class="columns">
para hacerlo más semántico puedes cambiar el div por un section

2021-12-07 01:14 UTC, JosephColinP commented on ch7-multiple-columns/index.html
> +        <div class="columns">
vale, en breve lo arreglo

2021-12-07 01:29 UTC, JosephColinP commented on ch7-multiple-columns/css/styles.css
> +  margin: 0 auto;
será que paso el height y el width hasta el final?

2021-12-07 05:55 UTC, JosephColinP commented
> @JosephColinP en móvil por default siempre se muestra una sola columna.
> 
> Para optimizar el ancho del dispositivo y ayudar con la lectura de textos

Mañana checo esto :+1:

2021-12-16 15:59 UTC, semanticmx commented on ch7-multiple-columns/css/styles.css
> +  margin: 0 auto;
si, sería por orden alfabético.

[c]olumns
[h]eight
[m]argin
[w]idth

2021-12-16 16:01 UTC, JosephColinP commented on ch7-multiple-columns/css/styles.css
> +  margin: 0 auto;
Ahorita lo corrigo

2021-12-16 16:59 UTC, semanticmx approved these changes

2021-12-16 17:00 UTC, merged